{{ $operator := .Values.grafanaOperator }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-operator
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "grafana.labels" . | indent 4 }}
spec:
  replicas: {{ $operator.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "grafana.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ $operator.serviceAccount.name }}
      containers:
      - name:  grafana-operator
        image: "{{ $operator.image.repository }}:{{ $operator.image.tag }}"
        imagePullPolicy: {{ $operator.image.pullPolicy }}
        ports:
        - containerPort: 60000
          name: metrics
        command:
        - grafana-operator
        args:
        - --scan-all
        readinessProbe:
          exec:
            command:
              - stat
              - /tmp/operator-sdk-ready
          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        env:
        - name: TEMPLATE_PATH
          value: /usr/local/bin/templates
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "grafana-operator"
