{{ $grafana := .Values.grafana }}
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  deployment:
    labels:
      app.kubernetes.io/name: {{ include "grafana.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app: {{ .Release.Namespace }}
    replicas:  {{ $grafana.replicaCount }}
  ingress:
    enabled: {{ $grafana.ingress.enabled }}
    hostname: {{ tpl ($grafana.ingress.hostname) . }}
    tlsEnabled: {{ $grafana.ingress.tls }}
    path: "/"
    annotations:
    {{- with $grafana.ingress.annotations -}}
    {{- toYaml . | trim | nindent 6 }}
    {{- end }}
  client: 
    preferService: {{ $grafana.client.preferService }}
  config:
  {{- with  $grafana.configs  }}
  {{- toYaml . | trim | nindent 4 }}
  {{ end }}
  dashboardLabelSelector:
    - matchExpressions:
        - {key: app, operator: In, values: [grafana]}
