apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    helm.sh/chart: {{ include "grafana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
  name: {{ include "grafana.fullname" . }}-operator
type: Opaque
data:
  gf_password: {{ .Values.grafana.configs.security.admin_password | b64enc }}
---
